name: QR Attendance System CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  # Backend Tests
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: qr_attendance_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, pgsql
        coverage: xdebug

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        composer install --prefer-dist --no-interaction --no-progress

    - name: Copy Environment File
      working-directory: ./backend
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Configure Database
      working-directory: ./backend
      run: |
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=qr_attendance_test_db/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=postgres/' .env

    - name: Run Migrations
      working-directory: ./backend
      run: php artisan migrate --force

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload Backend Coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage

  # Frontend Tests
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Frontend Lint
      working-directory: ./frontend
      run: npm run lint

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm run test:coverage

    - name: Upload Frontend Coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Deploy to Staging (if on dev branch)
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-scan]
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Staging
      run: |
        echo "Deploy to staging environment"
        # Add actual deployment steps here

  # Deploy to Production (if on main branch)
  deploy-production:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Production
      run: |
        echo "Deploy to production environment"
        # Add actual deployment steps here
